// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	IsActive     pgtype.Bool
	IsSuperuser  pgtype.Bool
	Thumbnail    pgtype.Text
	DateJoined   pgtype.Timestamptz
}

type UserProfile struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	PhoneNumber interface{}
	BirthDate   pgtype.Date
}
