// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, first_name, last_name, is_active, is_superuser, thumbnail, date_joined)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, email, password_hash, first_name, last_name, is_active, is_superuser, thumbnail, date_joined
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	IsActive     pgtype.Bool
	IsSuperuser  pgtype.Bool
	Thumbnail    pgtype.Text
	DateJoined   pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.IsActive,
		arg.IsSuperuser,
		arg.Thumbnail,
		arg.DateJoined,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.Thumbnail,
		&i.DateJoined,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profile (user_id, phone_number, birth_date)
VALUES ($1,$2,$3)
RETURNING id, user_id, phone_number, birth_date
`

type CreateUserProfileParams struct {
	UserID      pgtype.UUID
	PhoneNumber interface{}
	BirthDate   pgtype.Date
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile, arg.UserID, arg.PhoneNumber, arg.BirthDate)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhoneNumber,
		&i.BirthDate,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, first_name, last_name, is_active, is_superuser, thumbnail, date_joined
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsSuperuser,
		&i.Thumbnail,
		&i.DateJoined,
	)
	return i, err
}
